### ISSUE TITLE
SAGU - Residência Multiprofissional - Detalhar Relatório de frequência do residente (presença e falta)

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/sagu#26]

**Comment by vicmagpac** [comment]
Iniciando implementação do relatório.

**Comment by vicmagpac** [comment]
Dados necessários: 
![Captura de tela de 2020-10-19 09-09-43](https://user-images.githubusercontent.com/3487411/96449235-ef50c700-11ea-11eb-87c1-00842ebaeac4.png)

**Comment by vicmagpac** [comment]
Concluído com sucesso! Em processo de envio pra produção.

**Comment by vicmagpac** [comment]
Em produção.
