### ISSUE TITLE
[BUG] - Geração caderno de chamada problema - 504

### ISSUE THREAD

**Issue by vicmagpac** [EscolaDeSaudePublica/sagu#69]
### Problema 

Bug na geração do caderno de chamada dentro do módulo de ensino, pesquisa e extensão.

Curso: 104
Turma: Todas

Usuários estão precisando gerar o documento para prosseguir com fluxo interno no setor.

**Comment by vicmagpac** [comment]
Print do bug:
![1db995d3-aa6d-41a3-abfb-64db6f78983d](https://user-images.githubusercontent.com/3487411/100455126-f3e78580-309c-11eb-817b-8ba224ed0e2a.jpeg)

**Comment by victorMagalhaesPacheco** [comment]
@victorMagalhaesPacheco Pessoal, essa é um problema que está acontecendo em produção. Estou informando pois acredito que é importante todos estarmos alinhados.

**Comment by vicmagpac** [comment]
Problema resolvido com sucesso em produção.
