### ISSUE TITLE
Propostas e avaliações em tempo de implementação

### ISSUE THREAD

**Issue by vicmagpac** [EscolaDeSaudePublica/sagu#79]
# Contextualização

Baseado na necessidade de implementação da descentralização do acompanhamento da residência multiprofissional por parte dos supervisores, foi necessário pensar e propor uma arquitetura que integre os sistemas SAGU, SAGU API e iSUS de forma a atender todos os requisitos funcionais e não funcionais solicitado pela área da residência multiprofissional.

A reunião sobre o refinamento aconteceu no dia 06/05/2021 às 10h com a presenção do @chicaothiago  @victorMagalhaesPacheco 

## Objetivos

Apresentar propostas de arquiteturas baseados nos requisitos funcionais e não funcionais.

# Resultados

### Proposta 1

```
@startuml sagu
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(supervisor, "Supervisor")

System_Boundary(sagu, "Sagu") {
    Container(sagumiolo, "SAGU Miolo", "PHP")
    ContainerDb(bancosagu, "Banco de dados", "PostgreSQL", "Banco de dados do SAGU")

    Rel(sagumiolo, bancosagu, "Acessa ao banco");
}

System_Boundary(apisagu, "Sagu API") {
    Container(sagulumen, "SAGU Lumen", "Lumen")

    Rel(sagulumen, bancosagu, "Acessa ao banco da residência médica e residência multiprofissional");
}

System(isus, "iSUS", "Aplicativo para profissionais de Saúde")

Rel(sagulumen, isus, "Integra acompanhamento de frequência e notas dos residentes ", "RestFul");

Rel(supervisor, isus, "Acompanhamento do residente por parte do supervisor");

@enduml
```

![sagu](https://user-images.githubusercontent.com/3487411/117313949-b7defa80-ae5c-11eb-80b5-efd907862edd.png)

**Pontos positivos**

1. Integração 100% ao iSUS

**Pontos negativos**

1. Acesso será somente pelo app
2. Não terá acesso pelo browser (requisito não funcional)
3. Para cada alteração na funcionalidade da residência multiprofissional será um build novo

### Proposta 2

```
@startuml sagu
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(supervisor, "Supervisor")

System_Boundary(sagu, "Sagu") {
    Container(sagumiolo, "SAGU Miolo", "PHP")
    ContainerDb(bancosagu, "Banco de dados", "PostgreSQL", "Banco de dados do SAGU")

    Rel(sagumiolo, bancosagu, "Acessa ao banco");
}

System_Boundary(apisagu, "Sagu API") {
    Container(sagulumen, "SAGU Lumen", "Lumen")

    Rel(sagulumen, bancosagu, "Acessa ao banco da residência médica e residência multiprofissional");
}

System(sagufront, "Sagu Front", "Front da residência multiprofissional", "React")
Rel(sagufront, sagulumen, "Acompanhamento do residente por parte do supervisor");

System(isus, "iSUS", "Aplicativo para profissionais de Saúde")

Rel(isus, sagufront, "Redireciona para o acompanhamento da residência multiprofissional", "WebView");

Rel(supervisor, isus, "Acessa o iSUS");
Rel(supervisor, sagufront, "Acompanhamento do residente por parte do supervisor");

@enduml
```

![sagu](https://user-images.githubusercontent.com/3487411/117314911-98949d00-ae5d-11eb-9b19-7a9a0a21ebc7.png)

**Pontos positivos**

1. Acesso pelo browser (requisito não funcional)
2. Responsivo
3. Acesso pelo iSUS (webview)
4. Para cada atualização não será necessário gerar um novo build do app

**Pontos negativos**

1. Implementação de um novo cliente não existente

## Issues relacionadas
#28

**Comment by uira** [comment]
@victorMagalhaesPacheco É aqui que vota na #Proposta02 ?
