### ISSUE TITLE
Envio de e-mails (notificações e recuperação de senha) não funciona

### ISSUE THREAD

**Issue by vicmagpac** [EscolaDeSaudePublica/sagu#86]
# Contexto
## O que originou

Envio de email parou de funcionar no SAGU. Notificações de inscrições, cadastros dos alunos e recuperação de senha parou de funcionar.

## Qual solução proposta

Possivelmente são as credenciais do SMTP, necessário verificar com a infra.

**Comment by victorMagalhaesPacheco** [comment]
![Uploading Captura de tela de 2021-06-29 11-22-00.png…]()

**Comment by vicmagpac** [comment]
![Captura de tela de 2021-06-29 11-22-00](https://user-images.githubusercontent.com/3487411/123814698-48214500-d8cc-11eb-980e-e9cb7d413e10.png)

**Comment by vicmagpac** [comment]
Problema resolvido coms ucesso.
