### ISSUE TITLE
Retirada ou adição de obrigatoriedade no banco de dados para API do SAGU.

### ISSUE THREAD

**Issue by nestorufpe** [EscolaDeSaudePublica/sagu#90]
## **Contexto**

Dado que existem dados obrigatórios hoje divergentes entre alunos inscritos no MAPA e pessoa física no SAGU (como por exemplo, entre sexo no SAGU e Gênero no MAPA). Se faz necessário a retirada de obrigatoriedade de alguns desse campos no banco de dados do SAGU para cadastramento automático de pessoa física diretamente no banco de dados do SAGU. 

## **Fora de Escopo**

- [ ] 

## **Critérios de Aceitação**

- [x] Manter obrigatório apenas dados essenciais como nome, sobrenome, data de nascimento, endereço, formação profissional, CPF e RG
**Dado que** API do SAGU
**Quando** requisitado pelo plugin do MAPA
**então** será realizado o castrado automático de pessoa física no SAGU

## Observações
Links de apoio e informações adicionais

**Comment by ricardopoppi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Integraes-de-Produtos-622f81f2eaf7c70010bd1495/issues/EscolaDeSaudePublica/sagu/90?planning-poker) with ZenHub @victorMagalhaesPacheco
