### ISSUE TITLE
Implementar na api do sagu as regras de negócio para efetuar o cadastramento de pessoa física

### ISSUE THREAD

**Issue by nestorufpe** [EscolaDeSaudePublica/sagu#91]
## **Contexto**

Preparar endpoint na API do SAGU para receber dados de inscritos no MAPA para casdrasmento automático de pessoa fisíca no SAGU. 

## **Fora de Escopo**

- [ ] 

## **Critérios de Aceitação**

- [x] Preparar endpoint na API do SAGU
**Dado que**  API do SAGU
**Quando** requisitada, faça inserção de dados (Nome, sobrenome, CPF, RG, formação profissional, telefone, celular, sexo, data de nascimento, endereço)
**então** será realizado o cadastro de pessoa física no banco de dados no SAGU

## Observações
Links de apoio e informações adicionais

**Comment by ricardopoppi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Integraes-de-Produtos-622f81f2eaf7c70010bd1495/issues/EscolaDeSaudePublica/sagu/91?planning-poker) with ZenHub @victorMagalhaesPacheco
